openapi: 3.0.0
info:
  title: user
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userid}':
    parameters:
      - type: string
        name: userid
        in: path
        schema:
          type: integer
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/user-partial.v1.json
      operationId: 'get-users-{userid}'
    delete:
      summary: ''
      operationId: 'delete-users-{userid}'
      responses:
        '204':
          description: No Content
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/user-full.v1.json
              examples:
                application/json:
                  value:
                    - id: 1
                      name: Yogesh
                    - id: 2
                      name: monty
      operationId: get-users
    post:
      summary: ''
      operationId: post-users
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/user-full.v1.json
components:
  schemas: {}
  securitySchemes: {}
