openapi: '3.0.0'
info:
  title: order
  version: '1.0'
servers:
- url: http://localhost:3000
paths: {}
components:
  schemas:
    x-tags:
      - Orders
    title: Order
    description: A list of order.
